### ISSUE TITLE
Styling notice boxes - 10%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#24]
We already created a Notice component in [this PR](https://github.com/pinglue/site/issues/2) to display a notice.

In this task we want to style the Notice component to look nice.

We need these "types" of notice boxes:
1. tip
2. recall
3. info
4. warning
5. prerequisite

And we may have more types ... As for styling, they all have the same style except for their background color and the icon. For a sample design you can see the prerequisite box [here](https://redux.js.org/tutorials/quick-start) (which is a colored box with icon, title which is the same as the type, and the body which is the content)

Just pick a color and icons for each type (maybe you can save them in an object or map?)

**Comment by yuki-tylar** [comment]
Does notice box mean sandbar / toastr kind of things?

![image](https://user-images.githubusercontent.com/32935311/150277923-2de1e09a-e8b9-48d7-9797-e8eaa6d5fafd.png)

**Comment by yuki-tylar** [comment]
I created pull request for this (not completed yet)

Once you merge another task `Design for doc page (html/css)` into main, I'll merge main into this branch so that I can use the Bootstrap icon and classes properly.

And I think it's better to control noticeBox using redux or context which I haven't implemented here yet.

other than that, noticeBox works properly.

**Comment by pmvald** [comment]
Maybe I forgot to mention, but you should refer to the [project page](https://github.com/orgs/pinglue/projects/1) to see which project you have to start with (the one in the middle column) - Assigning does not mean that the task is ready yet- Once the task becomes ready we move it to the middle column (in-progress) and then you can start. We also usually have one in-progress task per person, so that we do the tasks one by one

As for this task, yes you are almost correct we need those type of boxes - I'll give more details and samples when we move this task into in-progress - for now there are a few issues with the previous task and I created a task for that - please refer to the project page and get started on that - meanwhile I'll update this task and others with more details

**Comment by pmvald** [comment]
comments updated

**Comment by pmvald** [comment]
Another type we use a lot is "note" - which is similar to info, but it is to remind the reader of something - the color could be similar to info type but icon should be different

**Comment by yuki-tylar** [comment]
I found icons and show all type of notice boxes on right side bar.
Please check if it's suitable.

Please note...
* defined color using css-custom-property in project root css file (_project.scss) so that we can use it anywhere.
* merged main into this branch. I pushed all unnecessary files in different commit. When you review, please see `d9bccad` which contains only files which need to be reviewed.
* This Notice box doesn't have width / height / position setting, so we can also use it as sandbar / toastr. (we just need to create other wrapper component)
* I didn't delete `NoticeController` component which emulates sandbar just in case. but I guess this file is not necessary.
