### ISSUE TITLE
Close button for the TOC sidebar on mobile view - 10%

### ISSUE THREAD

**Issue by pmvald** [pinglue/site#46]
may be cross icon on the right side of the bar and in front of the title ?

**Comment by yuki-tylar** [comment]
Added close button.

I suggest...
* the button should be same position as hamburger menu. (main column has padding-2 and leftSideBar has padding-1 currently which should be padding-2?)
*  close button and also open button should be right side as same as flutter website (https://flutter.dev/?gclid=CjwKCAiA866PBhAYEiwANkIneBltCR0DuWtvV2037kx8Kepy379pL8yDfxgyGcZbJxaPUWpOkO86tBoCIf8QAvD_BwE&gclsrc=aw.ds). Otherwise doc title position is kind of weird in mobile view?

**Comment by pmvald** [comment]
> Added close button.
> 
> I suggest...
> 
> * the button should be same position as hamburger menu. (main column has padding-2 and leftSideBar has padding-1 currently which should be padding-2?)
> * close button and also open button should be right side as same as flutter website (https://flutter.dev/?gclid=CjwKCAiA866PBhAYEiwANkIneBltCR0DuWtvV2037kx8Kepy379pL8yDfxgyGcZbJxaPUWpOkO86tBoCIf8QAvD_BwE&gclsrc=aw.ds). Otherwise doc title position is kind of weird in mobile view?

Sounds good, we can follow flutter design - seems more modern.

**Comment by yuki-tylar** [comment]
I updated this branch.

* now leftSideBar is `100vw` when `mobileView`
* `closeButton` is moved to right.
* `iconBtn` is standardized as `.s-icon-btn` so that icon size is always big enough and button height is consistent

I'll change hamburger menu button style at another branch.
